### ISSUE TITLE
Installation issues on Ubuntu

### ISSUE THREAD

**Issue by David4631** [kebhr/scratch3-tello#6]
I'm a teacher in an association and I learn to code to children on Tello drone.

I have compile scratch3-tello on Ubuntu 21.04 on a raspberry pi and also on Lubuntu 20.04.3 on PC.
The result of this compilation is OK on the 2 platforms.
But when I launch scratch3-tello with "npm start", I obtain this 2 debug windows, same error messages in the console :
![Capture d’écran du 2021-09-22 19-51-31](https://user-images.githubusercontent.com/91215545/134396416-c30f7e58-af30-4e0f-86d8-9df383a8b1c7.png)
But I still can command Tello with Scratch.

And making the package with "npm run dist:dir" doesn't work :
![Capture d’écran du 2021-09-22 20-04-47](https://user-images.githubusercontent.com/91215545/134397778-9c4b90a6-1f24-4073-8adb-a2d611266de9.png)

The version of node and npm are the same in the 2 platforms :
![Capture d’écran du 2021-09-22 20-16-19](https://user-images.githubusercontent.com/91215545/134399358-4d0f21ba-abba-46d1-a07e-e571fc8ba5bf.png)

Thanks for this good job kebhr

**Comment by kebhr** [comment]
Hello. Thanks for the report.

## About the message "Failed to fetch extension"

Don't worry about this error.
This error is not related to operate scratch3-tello.
In-text "extension" means Chrome extension named React/Redux Developer Tools. These extension are installed via Chrome Webstore only when app starts by "npm start".
This error occurs because the Internet connection is disconnected in order to communicate with Tello.

## About the error with making the package with "npm run dist:dir"

I've confirmed that this problem is reproduced.
I'll work on fixing this problem.


I hope this software will be useful in educating children. Thanks.
